name: wmx-kiosk-session
version: '8'
summary: The superior wmx window manager in a busybox session for mir-kiosk
description: |
  wmx is a window manager for X. It's based on wm2,
  and it retains a similar look and feel, but it's
  intended to provide an experimental vehicle for
  features that fall comfortably outside the scope
  of the manifesto for the original wm2.

grade: stable
confinement: strict

apps:
  wmx:
    command: bin/launcher.sh
    environment:
      WAYLAND_SOCKET_DIR: $SNAP_DATA/wayland
      XWAYLAND_FULLSCREEN_WINDOW_HINT: title="wmx"
      FONTCONFIG_PATH: $SNAP/etc/fonts/config.d
      FONTCONFIG_FILE: $SNAP/etc/fonts/fonts.conf
    daemon: simple
    plugs:
      - x11-plug
      - wayland
      - opengl
      - network
      - network-bind
      - system-observe
      - log-observe
      - mount-observe
      - removable-media
      - network-observe
      - shutdown
      - timezone-control
      - time-control
      - hostname-control
    slots: [ x11 ]

plugs:
  wayland-socket-dir:
    content: wayland-socket-dir
    interface: content
    target: $SNAP_DATA/wayland
    default-provider: mir-kiosk
  x11-plug:
    interface: x11

parts:
  wmx:
    after: [ xwayland-kiosk-helper ]
    source: http://www.all-day-breakfast.com/wmx/wmx-8.tar.gz
    plugin: nil
    override-build: |
      ./configure --prefix=$SNAPCRAFT_PART_INSTALL
      # enable clock
      sed -i 's/#define CONFIG_CLOCK.\{14\}False/#define CONFIG_CLOCK\t\t  True/' Config.h
      # set our own cursor
      sed -i 's/#define CONFIG_USE_PLAIN_X_CURSORS\tTrue/#define CONFIG_USE_PLAIN_X_CURSORS\tFalse/' Config.h
      # change terminal command
      sed -i 's/x-terminal-emulator/launchterm/' Config.h
      # rename "New" to "New Terminal"
      sed -i 's/\"New\"/\"New Terminal\"/' Config.h
      # swich default font
      sed -i 's/Bitstream Vera Sans/DejaVu Sans/' Config.h
      # drop useless chown
      sed -i 's/-chown/#-chown/' Makefile
      make
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      make install
      cp ../../../launcher.sh $SNAPCRAFT_PART_INSTALL/bin
      cp ../../../launchterm $SNAPCRAFT_PART_INSTALL/bin
    build-packages:
      - libfontconfig1-dev
      - libice-dev
      - libsm-dev
      - libx11-dev
      - libxau-dev
      - libxcb1-dev
      - libxcomposite-dev
      - libxdmcp-dev
      - libxext-dev
      - libxft-dev
      - libxpm-dev
      - libxrender-dev
      - xfonts-utils
    stage-packages:
      - busybox-static
      - bsdutils
      - dropbear-bin
      - fontconfig
      - fonts-dejavu-core
      - libsm6
      - libice6
      - libx11-6
      - libxau6
      - libxcomposite1
      - libxdmcp6
      - libxext6
      - libxft2
      - libxpm4
      - libxrender1
      - libfontconfig1
      - libxcb1
      - rxvt-unicode
      - xfonts-75dpi
      - xfonts-100dpi
      - xfonts-base
      - xfonts-scalable
      - xfonts-unifont
      - x11-apps
      - x11-xserver-utils
  x11fonts:
    plugin: nil
    after: [ wmx ]
    override-prime: |
      for dir in X11/misc X11/Type1 X11/75dpi X11/100dpi truetype/dejavu; do
        cd usr/share/fonts/$dir
        mkfontscale
        mkfontdir
        cd - >/dev/null
      done
      snapcraftctl prime
